### ISSUE TITLE
This looks great!

### ISSUE THREAD

**Issue by TomasVotruba** [eonx-com/easy-monorepo#225]
Hey, just bumped into this. Is that something like a monorepo sand-box?
It looks really great! :clap: Where did you share it? Post? Tweet? 

It could be great starting point to learn what monorepo is in real life.

Do you need some help to set continous intergration (ECS, Rector, PHPStan) up?

**Comment by natepage** [comment]
Hi @TomasVotruba! Thank you for the message, really appreciate it, I'm curious to know how did you end up here!? 😄 

So it's not a sand-box, it is an actual monorepo we're using at EonX to develop packages for our projects.

Where did we share it? Nowhere.. Lucky us, our company is doing great, lots of projects to build, lots of work to do, so documentation and communication have been left behind. This is why we are now playing catch-up! 😄 

We've recently started to put some documentation together (be nice it's a work in progress 😄) and we've used your new Symfony Static Dumper, you can find the result there: https://packages.eonx.com/

All packages in this monorepo have been built to first respond to a business requirement but we've built them in an "open-source" way, we've tried not to be too opinionated, the core logic is framework agnostic and we have bridges for the Laravel and Symfony.

In term of CI we are using github actions with the following tools: ECS, PHPStan, Rector and Symfony SecurityChecker. We've put in place internal coding standards, and because we start to have a few projects we've decided to centralise the custom sniffs, fixers and rectors into a package that each project can re-use: https://github.com/eonx-com/easy-monorepo/tree/master/packages/EasyStandard

And we try to stay up-to-date with all the updates you post such as Split testing: https://github.com/eonx-com/easy-monorepo/blob/master/.github/workflows/split_tests.yml

So as you can see, we've heavily used your tools and thank you for making them!

And yes it would be great to be able to have your opinion on things!

**Comment by TomasVotruba** [comment]
Ah, it's not "Easy" as in EasyCodingStandard, but rather compony monorepo.

I think it's great your company has someone like you to tidy up things. Most devs just pile up lines of code and then leave place in total mess. 

Keep up cleaning! So far it's looks great!

**Comment by natepage** [comment]
Yes you're right it is a company monorepo. "Easy" comes from "EasyCodingStandard" tho as most of those packages improves DX and make things "easy" to do. And then my OCDs made me prefix each package with "Easy" as I like when things are consistent. But maybe something to change later 😄 

But this monorepo is only a "side project" to help the other projects, we have 10+ PHP applications that we've created over the past 2 years so we have:

- different PHP versions (from 7.1 to 7.4)
- different frameworks (Laravel, Lumen, Symfony)
- different versions of those frameworks (Laravel 5.6, Lumen 6+, Symfony 4.4 to 5+)

Like I said before we're putting the effort to clean up all that, and I think that we are on the right track but I believe that it would be highly beneficial for us to have someone else point of view, especially with your expertise.

Most of those projects are private so we should take it offline from here, if you are interested in doing business with us please send me an email at nathan.page@eonx.com

Regards.
