### ISSUE TITLE
[EasySearch] Create package

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#244]
Create a package to make exposing search endpoints easier.

This package MUST take care only about the searching functionality as the syncing of external service would be done by third party service (e.g. logstash)

**Comment by natepage** [comment]
@roman-eonx @egor-dev @dextercampos @albertlabarentojr 

I've just created a PR to add a simple search service to `easy-core`, it replicates what the search package is doing but isn't responsible for:

- resolve the index name
- generate the HTTP response

I've designed it this way on purpose so it doesn't depend on the request object and doesn't define how we respond to the consumer. This way this service can be called from anywhere not only a controller.

Can you guys please try it in your projects to identify major issues, and potentially improve it 😉 

You should be able to require the `dev-feature/search-in-easy-core` version.

**Comment by DKeeper** [comment]
@natepage Need to small update in` \EonX\EasyCore\Search\ElasticsearchSearchService` - change `'match_all' => []` to `'match_all' => new \stdClass()`, because `match_all` should be empty object after encoding a value (more details here - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-all-query.html).
1. Value as empty array
`['query'=>['bool' => ['must' => $query ?? ['match_all' => []],'filter' => [['terms' => ['test' => 'anonymous']]]]]]`
encoded string
`{"query":{"bool":{"must":{"match_all":[]},"filter":[{"terms":{"test":"anonymous"}}]}}}`
2. Value as empty class
`['query'=>['bool' => ['must' => $query ?? ['match_all' => new \stdClass()],'filter' => [['terms' => ['test' => 'anonymous']]]]]]`
encoded string
`{"query":{"bool":{"must":{"match_all":{}},"filter":[{"terms":{"test":"anonymous"}}]}}}`

**Comment by natepage** [comment]
@DKeeper Nice one, feel free to push an update to the PR branch 😉

**Comment by DKeeper** [comment]
@natepage Done.

**Comment by natepage** [comment]
@DKeeper I've pushed the changes to the version of that branch so you can test in your projects.

**Comment by dextercampos** [comment]
@natepage We've tried `dev-feature/search-in-easy-core` in our projects and so far no more issues found.

**Comment by natepage** [comment]
It was decided to implement a search service in `eonx-com/easy-core` for now, and it has been done.
